%YAML:1.2
countdown: 5
initial_countdown: 10

motion_interval: 0.02

frame_spacing: 0.5

satisfied_pause: 10.0

output_dir: archive

minimum_area: 0.3
max_allowed_area: 0.8
acculum_weight: 0.33
motion_score_threshold: 10

sounds:
    begin:
        sounds/borg_tractor_beam.mp3
    tick:
        sounds/romulan_computerbeep1.mp3
    shot:
        sounds/tos_keypress3.mp3
