%YAML:1.2

debug: false

# Which camera to open, zero-based device id.
camera_id: 0

# Seconds to countdown between captures.
countdown: 5
# First countdown duration in a volley, in seconds.
initial_countdown: 10

# TODO: num_volleys

# Polling interval for realtime video, in seconds.  Higher values will
# use less processor on older hardware, lower values will be more
# responsive.
# TODO: Lag time goes up too quickly, there is a bug here.
motion_interval: 0.02

# How long each shot is displayed after taken, in seconds.
frame_pause: 0.5

# Pause while the final collage is displayed, in seconds.
satisfied_pause: 10.0

# Directory path where image files will be written.
output_dir: ~/photo-booth-archive

# Motion detection settings.
# TODO: These numbers are twitchy, narrow ranges work at all.
# TODO: This should adapt to light and contrast conditions,
# but does not.
minimum_area: 0.3
max_allowed_area: 0.8
acculum_weight: 0.33
motion_score_threshold: 10

# Allow manual trigger by hitting a key?
key_trigger: true

# Commandline to play a sound file.  Adjust if you want to use
# a player other than the default.
sound_cmd: "play -q %s"

# Path to sound effect files.
# TODO: relative path fail?
sounds:
    # Played when the motion detection threshold is tripped.
    begin: "116505__owdeo__transporter-beam.flac"

    # Capture is happening now.
    shot: "104291__ryansnook__klaxon3.flac"

    # Countdown second has passed.
    tick: "254316__jagadamba__clock-tick.flac"
